site_name: SC-machine

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - Installation with Docker: docker.md
  - Build:
      - Build on Linux: build/linux-build.md
      - Build on OSX: build/osx-build.md
      - CMake flags: build/cmake-flags.md
      - Configuration file: build/config.md
  - API:
      - C++ API: sc-memory/api/cpp-api.md
      - C++ Agents: sc-memory/api/cpp-agents.md
      - sc-element types: sc-memory/api/sc-element-types.md
      - SCs language: scs/scs.md
  - Tools:
      - Knowledge Base Builder: sc-tools/kb-builder.md
      - Knowledge Base repo file: sc-tools/kb-repo-file.md
      - Meta programming: sc-tools/cpp-meta.md
  - Development:
      - Git-workflow: dev/git-workflow.md
      - Codestyle: dev/codestyle.md
      - Dev container: dev/devcontainer.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
