site_name: SC-machine

extra_css:
  - _assets/main.css
extra_javascript:
  - _assets/scg.min.js
  - _assets/main.js

nav:
  - Home: index.md
  - Installation with Docker: docker.md
  - Build:
      - Build on Linux: build/linux-build.md
      - Build on OSX: build/osx-build.md
      - CMake flags: build/cmake-flags.md
      - Configuration file: build/config.md
  - API:
      - C++ API:
          - C++ Core API: sc-memory/api/cpp/core/api.md
          - C++ Extended API:
              - System identifier API: sc-memory/api/cpp/extended/helper-api.md
              - ScTemplate API: sc-memory/api/cpp/extended/template-api.md
          - C++ Agents API: sc-memory/api/cpp/agents.md
      - Python API:
          - Python Core API: https://github.com/ostis-ai/py-sc-client
          - Python Extended API: https://github.com/ostis-ai/py-sc-kpm
      - TypeScript API:
          - TypeScript Core API: https://github.com/ostis-ai/ts-sc-client
      - Sc-element types: scs/sc-element-types.md
      - SCs-code: scs/scs.md
  - Tools:
      - Knowledge Base Builder: sc-tools/sc-builder.md
      - Knowledge Base repo file: sc-tools/kb-repo-file.md
      - Websocket server: sc-tools/sc-server.md
      - Meta programming: sc-tools/cpp-meta.md
  - Development:
      - Git-workflow: dev/git-workflow.md
      - Codestyle: dev/codestyle.md
      - Dev container: dev/devcontainer.md
  - License: license.md
  - Changelog: changelog.md
  - Thirdparty: thirdparty.md

theme: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
